-- Create candidate_data table
CREATE TABLE IF NOT EXISTS public.candidate_data (
    id BIGINT PRIMARY KEY,
    name TEXT,
    subtitle TEXT,
    dob TEXT,
    position TEXT,
    unit TEXT,
    "yearsOfWork" INTEGER,
    qualifications TEXT,
    achievements TEXT,
    bio TEXT,
    intro TEXT,
    "avatarUrl" TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- If the table already exists, add the bio column
ALTER TABLE public.candidate_data ADD COLUMN IF NOT EXISTS bio TEXT;

-- Create achievements_files table
CREATE TABLE IF NOT EXISTS public.achievements_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT,
    "fileName" TEXT,
    "fileUrl" TEXT,
    "fileType" TEXT,
    size BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create survey_responses table
CREATE TABLE IF NOT EXISTS public.survey_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    position TEXT,
    unit TEXT,
    q1 TEXT,
    q2 JSONB,
    q3 TEXT,
    q4 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Set up Row Level Security (RLS)
-- Allow public read access
ALTER TABLE public.candidate_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on candidate_data" ON public.candidate_data FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update on candidate_data" ON public.candidate_data FOR ALL USING (true);

ALTER TABLE public.achievements_files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on achievements_files" ON public.achievements_files FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update on achievements_files" ON public.achievements_files FOR ALL USING (true);

ALTER TABLE public.survey_responses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on survey_responses" ON public.survey_responses FOR SELECT USING (true);
CREATE POLICY "Allow public insert on survey_responses" ON public.survey_responses FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update/delete on survey_responses" ON public.survey_responses FOR ALL USING (true);

-- Insert default candidate data if not exists
INSERT INTO public.candidate_data (id, name, subtitle, dob, position, unit, "yearsOfWork", qualifications, achievements, bio, intro, "avatarUrl")
VALUES (
    1, 
    'Lê Thị Thanh Nhã', 
    'Ứng viên đề nghị xét tặng danh hiệu "Nhà giáo Ưu Tú"', 
    '1980-01-01', 
    'Giáo viên', 
    'Trường THPT', 
    20, 
    'Thạc sĩ Giáo dục', 
    'Chiến sĩ thi đua cơ sở, Bằng khen của Bộ Giáo dục', 
    'Cô Lê Thị Thanh Nhã là một nhà giáo tận tâm, luôn nỗ lực trong công tác giảng dạy và bồi dưỡng học sinh.',
    '<p>Nhập thành tích đạt được tại đây...</p>', 
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=256&h=256'
) ON CONFLICT (id) DO NOTHING;
